<a href="https://colab.research.google.com/github/abhishekCode7266/CodeC_technologies_Task/blob/main/Data_cleaning_%26_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Problem Statement***

The dataset containg missing value ,inconsistent data type and unnecessary infoemation that can affect analysis and machine learning performance.

In [34]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv("TitanicDataset.csv")
print("Dataset loaded successfully.")

print("\nInitial DataFrame head:")
display(df.head())
print("\nInitial DataFrame info:")
display(df.info())

Dataset loaded successfully.

Initial DataFrame head:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath",female,NaN,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Initial DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  13 non-null     int64
 1   Survived     13 non-null     int64
 2   Pclass       13 non-null     int64
 3   Name         13 non-null     object
 4   Sex          13 non-null     object
 5   Age          11 non-null     float64
 6   SibSp        13 non-null     int64
 7   Parch        13 non-null     int64
 8   Ticket       13 non-null     object
 9   Fare         12 non-null     float64
 10  Cabin        5 non-null      object
 11  Embarked     13 non-null     object
dtypes: float64(2), int64(5), object(5)
memory usage: 1.3+ KB

None

In [36]:
print("DataFrame shape:")
display(df.shape)

DataFrame shape:

(13, 12)

In [37]:
print("DataFrame information:")
display(df.info())

DataFrame information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  13 non-null     int64
 1   Survived     13 non-null     int64
 2   Pclass       13 non-null     int64
 3   Name         13 non-null     object
 4   Sex          13 non-null     object
 5   Age          11 non-null     float64
 6   SibSp        13 non-null     int64
 7   Parch        13 non-null     int64
 8   Ticket       13 non-null     object
 9   Fare         12 non-null     float64
 10  Cabin        5 non-null      object
 11  Embarked     13 non-null     object
dtypes: float64(2), int64(5), object(5)
memory usage: 1.3+ KB

None

In [38]:
print("Missing values before handling:")
display(df.isnull().sum())

# Fill missing 'Age' values with the median
if 'Age' in df.columns and df['Age'].isnull().any():
    median_age = df['Age'].median()
    df['Age'] = df['Age'].fillna(median_age)
    print(f"Filled missing 'Age' values with median: {median_age}")

# Fill missing 'Embarked' values with the mode
if 'Embarked' in df.columns and df['Embarked'].isnull().any():
    mode_embarked = df['Embarked'].mode()[0]
    df['Embarked'] = df['Embarked'].fillna(mode_embarked)
    print(f"Filled missing 'Embarked' values with mode: {mode_embarked}")

# Fill missing 'Fare' values with the median
if 'Fare' in df.columns and df['Fare'].isnull().any():
    median_fare = df['Fare'].median()
    df['Fare'] = df['Fare'].fillna(median_fare)
    print(f"Filled missing 'Fare' values with median: {median_fare}")

print("\nMissing values after handling (Age, Embarked, Fare):")
display(df.isnull().sum())

Missing values before handling:

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            2
SibSp          0
Parch          0
Ticket         0
Fare           1
Cabin          8
Embarked       0
dtype: int64

Filled missing 'Age' values with median: 26.0
Filled missing 'Fare' values with median: 16.10415

Missing values after handling (Age, Embarked, Fare):

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          8
Embarked       0
dtype: int64

In [42]:
# Drop 'Cabin' column due to a high number of missing values (or if deemed unnecessary)
if 'Cabin' in df.columns:
    # Determine if 'Cabin' has a significant number of missing values to warrant dropping
    # For this example, let's assume we drop it if it has more than 50% missing data
    if df['Cabin'].isnull().sum() / len(df) > 0.5:
        df = df.drop("Cabin", axis=1)
        print("Dropped 'Cabin' column due to many missing values.")
    else:
        print("'Cabin' column retained (less than 50% missing values).")
else:
    print("'Cabin' column not found in DataFrame.")

Dropped 'Cabin' column due to many missing values.

In [43]:
# Check for and remove duplicate rows
duplicate_rows = df.duplicated().sum()
print(f"Number of duplicate rows found: {duplicate_rows}")

if duplicate_rows > 0:
    df = df.drop_duplicates()
    print(f"Removed {duplicate_rows} duplicate rows. New shape: {df.shape}")
else:
    print("No duplicate rows found.")

Number of duplicate rows found: 1
Removed 1 duplicate rows. New shape: (12, 11)

In [55]:
# Convert 'Age' to numeric, coercing errors to NaN if any non-numeric values exist
if 'Age' in df.columns:
    df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
    print("Converted 'Age' to numeric type.")

# Convert 'Fare' to numeric, coercing errors to NaN if any non-numeric values exist
if 'Fare' in df.columns:
    df['Fare'] = pd.to_numeric(df['Fare'], errors='coerce')
    print("Converted 'Fare' to numeric type.")

# Convert 'Sex' to category type
if 'Sex' in df.columns:
    df['Sex'] = df['Sex'].astype('category')
    print("Converted 'Sex' to category type.")

# Convert 'Embarked' to category type
if 'Embarked' in df.columns:
    df['Embarked'] = df['Embarked'].astype('category')
    print("Converted 'Embarked' to category type.")

# Also convert 'Survived' and 'Pclass' to category as per original plan
if 'Survived' in df.columns:
    df['Survived'] = df['Survived'].astype('category')
    print("Converted 'Survived' to category type.")

if 'Pclass' in df.columns:
    df['Pclass'] = df['Pclass'].astype('category')
    print("Converted 'Pclass' to category type.")

print("\nDataFrame info after type conversions:")
display(df.info())

DataFrame info after type conversions:
<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 0 to 11
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   passenger_id      12 non-null     int64
 1   survived          12 non-null     category
 2   passenger_class   12 non-null     category
 3   name              12 non-null     object
 4   sex               12 non-null     category
 5   age               12 non-null     float64
 6   siblings_spouses  12 non-null     int64
 7   parents_children  12 non-null     int64
 8   ticket            12 non-null     object
 9   fare              12 non-null     float64
 10  embarked          12 non-null     category
dtypes: category(4), float64(2), int64(3), object(2)
memory usage: 1.3+ KB

None

In [49]:
# Rename columns for consistency and readability
new_column_names = {
    "PassengerId": "passenger_id",
    "Survived": "survived",
    "Pclass": "passenger_class",
    "Name": "name",
    "Sex": "sex",
    "Age": "age",
    "SibSp": "siblings_spouses",
    "Parch": "parents_children",
    "Ticket": "ticket",
    "Fare": "fare",
    "Embarked": "embarked"
}

# Apply renaming only to columns that exist in the DataFrame
df = df.rename(columns={col: new_name for col, new_name in new_column_names.items() if col in df.columns})

print("Columns renamed.")
print("\nDataFrame columns after renaming:")
display(df.columns)

Columns renamed.

DataFrame columns after renaming:

Index(['passenger_id', 'survived', 'passenger_class', 'name', 'sex', 'age',
       'siblings_spouses', 'parents_children', 'ticket', 'fare', 'embarked'],
      dtype='object')

In [50]:
print("Final check for missing values:")
display(df.isnull().sum())

Final check for missing values:

passenger_id        0
survived            0
passenger_class     0
name                0
sex                 0
age                 0
siblings_spouses    0
parents_children    0
ticket              0
fare                0
embarked            0
dtype: int64

In [51]:
print("Cleaned DataFrame head:")
display(df.head())

Cleaned DataFrame head:

,passenger_id,survived,passenger_class,name,sex,age,siblings_spouses,parents_children,ticket,fare,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath",female,26.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [52]:
print("Final DataFrame info:")
display(df.info())

Final DataFrame info:
<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 0 to 11
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   passenger_id      12 non-null     int64
 1   survived          12 non-null     category
 2   passenger_class   12 non-null     category
 3   name              12 non-null     object
 4   sex               12 non-null     category
 5   age               12 non-null     float64
 6   siblings_spouses  12 non-null     int64
 7   parents_children  12 non-null     int64
 8   ticket            12 non-null     object
 9   fare              12 non-null     float64
 10  embarked          12 non-null     category
dtypes: category(4), float64(2), int64(3), object(2)
memory usage: 1.3+ KB

None

In [53]:
output_filename = "Titanic_Cleaned.csv"
df.to_csv(output_filename, index=False)
print(f"Cleaned dataset saved as {output_filename}")

Cleaned dataset saved as Titanic_Cleaned.csv

In [54]:
print("Data cleaning completed successfully.")
print("Clean dataset saved as Titanic_Cleaned.csv")

Data cleaning completed successfully.
Clean dataset saved as Titanic_Cleaned.csv